routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
Route::get('/about', 'AboutController@index');
Route::get('/contact', 'ContactController@index');
Route::get('/works', 'WorksController@index');
Route::get('/works/{slug}', 'WorksController@getSingle');
Route::get('/hire', 'HireController@index');
Route::get('/hire/{slug}', 'HireController@details');

// Dashboard Admin
Route::group(['prefix' => "admin", 'middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('admin');

    /**
     * team
     */
    Route::resource('/team', 'Admin\TeamController', ['name' => 'team'])->except([
        'show', 'edit'
    ]);
    Route::post('team/sortable/', ['as' => 'team.sort', 'uses' => 'Admin\TeamController@sortTable']);

    /**
     * Client
     */
    Route::resource('/client', 'Admin\ClientController', ['name' => 'client'])->except([
        'show', 'edit'
    ]);
    Route::delete('client/imageDestroy/{id}', ['as' => 'client.imgdestroy', 'uses' => 'Admin\ClientController@imageDestroy']);
    Route::put('client/toggle/{id}', ['as' => 'client.toggle', 'uses' => 'Admin\ClientController@showHide']);
    Route::post('client/sortable/', ['as' => 'client.sort', 'uses' => 'Admin\ClientController@sortTable']);

    Route::resource('/{slug}/section', 'Admin\SectionController', ['name' => 'section'])->except([
        'index', 'create', 'show', 'edit'
    ]);
    Route::get('/{slug}/section/{id}', ['as' => 'section.index', 'uses' => 'Admin\SectionController@section']);

    /**
     * Job Hire
     */
    Route::resource('/hire', 'Admin\HireController', ['name' => 'hire']);
    Route::get('/hire/{slug}', ['as' => 'hire.detail', 'uses' => 'Admin\HireController@details']);
});
// Dashboard Admin -- END

// Auth route login to dashboard
Auth::routes([
    'register' => false,
    'reset' => false,
    'verivy' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
// Auth route login to dashboard -- END

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="en">
  @include('admin.header')
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  {{-- <div class="preloader flex-column justify-content-center align-items-center">
    <img class=" animation__wobble" src="{{asset('storage/laraassets/images/general/ozzigeno-logo.png')}}" alt="{{ config('app.name', 'Laravel') }}" width="200">
  </div> --}}

  <!-- Navbar -->
  @include('admin.navbar')

  <!-- Main Sidebar Container -->
  @include('admin.sidebar')

  <!-- Content Wrapper. Contains page content -->
  @include('admin.content')

  @include('admin.footer')

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

@include('admin.script')
</body>
</html>

resources/views/admin/content.blade.php
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          {{-- <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col --> --}}
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        
        @yield('content-dashboard')

      </div><!-- /.container-fluid -->
    </section>
  </div>

resources/views/admin/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2022 <a href="#">Ozzigeno</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
</footer>

resources/views/admin/header.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name', 'Laravel') }} | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('storage/adminlte') }}/plugins/fontawesome-free/css/all.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="{{ asset('storage/adminlte') }}/plugins/toastr/toastr.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('storage/adminlte') }}/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{ asset('storage/adminlte') }}/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('storage/adminlte') }}/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('storage/adminlte') }}/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
</head>

resources/views/admin/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-user"></i> | {{ Auth::user()->name }}
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a class="dropdown-item text-danger" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
              @csrf
          </form>
        </div>
      </li>
    </ul>
</nav>

resources/views/admin/script.blade.php
<!-- jQuery -->
<script src="{{ asset('storage/adminlte') }}/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('storage/adminlte') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- SweetAlert2 -->
{{-- <script src="{{ asset('storage/adminlte') }}/plugins/sweetalert2/sweetalert2.min.js"></script> --}}
<!-- Toastr -->
<script src="{{ asset('storage/adminlte') }}/plugins/toastr/toastr.min.js"></script>
<!-- bs-custom-file-input -->
<script src="{{ asset('storage/adminlte') }}/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<!-- JQVMap -->
<script src="{{ asset('storage/adminlte') }}/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="{{ asset('storage/adminlte') }}/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('storage/adminlte') }}/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('storage/adminlte') }}/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script>
  $(function () {
    bsCustomFileInput.init();
  });
</script>

{{-- Notification Controll --}}
@if ( session('message') )
  @if (session('message')['status'])
    <script>
      toastr.success("{{ session('message')['message'] }}")
    </script>
  @else
    <script>
      toastr.error("{{ session('message')['message'] }}")
    </script>
  @endif
@endif
@if ($errors->any())
    @foreach ($errors->all() as $err)
      <script>
        toastr.error("{{ $err }}")
      </script>
    @endforeach
@endif

<!-- Bootstrap Switch -->
<script src="{{ asset('storage/adminlte') }}/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>

<!-- AdminLTE App -->
<script src="{{ asset('storage/adminlte') }}/dist/js/adminlte.js"></script>

{{-- TinyMCE --}}
{{-- <script src="{{ asset('storage/js') }}/tinymce/tinymce.min.js" referrerpolicy="origin"></script> --}}
{{-- <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script> --}}
<script src="https://cdn.tiny.cloud/1/ryhja4ukez1ha3no4cry5pehequ184e8oyji2rsc8a4hx4g7/tinymce/5/tinymce.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.15.0/Sortable.min.js"></script>

<script src="{{ asset('storage') }}/laraassets/js/mainscript-dist.js"></script>

<script>
    // tinymce.init({
    //     selector: '#tinyMCE',
    //     menubar: false,
    //     plugins: "link image code",
    //     toolbar: 'undo redo | styleselect | forecolor | bold italic | alignleft aligncenter alignright alignjustify | outdent indent | link image | code',
    //     toolbar_location: 'bottom',
    // });
    tinymce.init({
      selector: '.tinyMCE',
      menubar: false,
      plugins: 'link image code lists',
      toolbar: 'undo redo | styleselect | forecolor | bullist | bold underline italic | alignleft aligncenter alignright alignjustify | outdent indent | link image | code',
      toolbar_mode: 'floating',
      tinycomments_mode: 'embedded',
      tinycomments_author: 'Author name',
    });

    $(function() {
      $("input[data-oz-switch]").each(function(){
        $(this).bootstrapSwitch('state', $(this).prop('checked'));
      })
    })
</script>

resources/views/admin/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{{asset('storage/laraassets/images/general/ozzigeno-logo.png')}}" alt="{{ config('app.name', 'Laravel') }} Logo" class="brand-image" style="opacity: .8">
        <span class="brand-text font-weight-light">{{ config('app.name', 'Laravel') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{{ asset('storage/adminlte') }}/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
            {{-- <li class="nav-header">MULTI LEVEL EXAMPLE</li>
            <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="fas fa-circle nav-icon"></i>
                <p>Level 1</p>
            </a>
            </li>
            <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-circle"></i>
                <p>
                Level 1
                <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Level 2</p>
                </a>
                </li>
                <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>
                    Level 2
                    <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Level 3</p>
                    </a>
                    </li>
                    <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Level 3</p>
                    </a>
                    </li>
                    <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Level 3</p>
                    </a>
                    </li>
                </ul>
                </li>
                <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Level 2</p>
                </a>
                </li>
            </ul>
            </li>
            <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="fas fa-circle nav-icon"></i>
                <p>Level 1</p>
            </a>
            </li> --}}
            <li class="nav-item">
                <a href="{{ route('team.index') }}" class="nav-link">
                    <i class="fas fa-user nav-icon"></i> 
                    <p>Team</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('client.index') }}" class="nav-link">
                    <i class="fas fa-file nav-icon"></i>
                    <p>Clients</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('hire.index') }}" class="nav-link">
                    <i class="fas fa-user-plus nav-icon"></i>
                    <p>Job Hire</p>
                </a>
            </li>
            {{-- <li class="nav-header">CONFIGURATION PAGES</li>
            <li class="nav-item">
                <a href="" class="nav-link">
                    <i class="fas fa-cog nav-icon"></i> 
                    <p>Pages <i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('work.index') }}" class="nav-link">
                            <i class="fas fa-file nav-icon"></i>
                            <p>Work</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="fas fa-file nav-icon"></i>
                            <p>About</p>
                        </a>
                    </li>
                </ul>
            </li> --}}
        </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
</aside>