routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index');
Route::get('/about', 'AboutController@index');
Route::get('/contact', 'ContactController@index');
Route::get('/works', 'WorksController@index');
Route::get('/works/{slug}', 'WorksController@getSingle');
Route::get('/hire', 'HireController@index');
Route::get('/hire/{slug}', 'HireController@details');

// Dashboard Admin
Route::group(['prefix' => "admin", 'middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('admin');

    /**
     * team
     */
    Route::resource('/team', 'Admin\TeamController', ['name' => 'team'])->except([
        'show', 'edit'
    ]);
    Route::post('team/sortable/', ['as' => 'team.sort', 'uses' => 'Admin\TeamController@sortTable']);

    /**
     * Client
     */
    Route::resource('/client', 'Admin\ClientController', ['name' => 'client'])->except([
        'show', 'edit'
    ]);
    Route::delete('client/imageDestroy/{id}', ['as' => 'client.imgdestroy', 'uses' => 'Admin\ClientController@imageDestroy']);
    Route::put('client/toggle/{id}', ['as' => 'client.toggle', 'uses' => 'Admin\ClientController@showHide']);
    Route::post('client/sortable/', ['as' => 'client.sort', 'uses' => 'Admin\ClientController@sortTable']);

    Route::resource('/{slug}/section', 'Admin\SectionController', ['name' => 'section'])->except([
        'index', 'create', 'show', 'edit'
    ]);
    Route::get('/{slug}/section/{id}', ['as' => 'section.index', 'uses' => 'Admin\SectionController@section']);

    /**
     * Job Hire
     */
    Route::resource('/hire', 'Admin\HireController', ['name' => 'hire']);
    Route::get('/hire/{slug}', ['as' => 'hire.detail', 'uses' => 'Admin\HireController@details']);
});
// Dashboard Admin -- END

// Auth route login to dashboard
Auth::routes([
    'register' => false,
    'reset' => false,
    'verivy' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
// Auth route login to dashboard -- END

resources/views/admin/modals/client-create.blade.php
<div class="modal fade" id="create" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Add new client</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('client.store') }}" method="post" autocomplete="off">
                    @csrf
                    <div class="form-group">
                        <label for="InputNamaClient">Nama Client</label>
                        <input type="text" name="brandName" class="form-control" id="InputNamaClient" placeholder="Nama Brand">
                    </div>
                    {{-- <div class="form-group">
                        <p class="text-gray">Slug : <span id="tagSlug">-</span></p>
                        <input type="hidden" name="brandSlug" class="form-control" id="InputSlug" placeholder="Slug">
                    </div> --}}
                    <div class="form-group">
                        <label for="InputService">Service</label>
                        <input type="text" name="brandService" class="form-control" id="InputService" placeholder="Service">
                    </div>
                    <div class="text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/client-delete.blade.php
<div class="modal fade" id="delete{{ $client->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus {{ $client->name }} ?</h5>
                <form action="{{ route('client.destroy', $client->id) }}" method="post">

                    @csrf
                    @method('DELETE')

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/client-image-delete.blade.php
<div class="modal fade" id="deleteImage-logo" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus logo {{ $client->name }} ?</h5>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->logo) }}" alt="{{ $client->name }}">
                <form action="{{ route('client.imgdestroy', $client->id) }}" method="post">

                    @csrf
                    @method('DELETE')
                    <input type="hidden" name="image" value="logo">

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteImage-background" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus background {{ $client->name }} ?</h5>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->background) }}" alt="{{ $client->name }}">
                <form action="{{ route('client.imgdestroy', $client->id) }}" method="post">

                    @csrf
                    @method('DELETE')
                    <input type="hidden" name="image" value="background">

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteImage-cover" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus cover {{ $client->name }} ?</h5>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->cover) }}" alt="{{ $client->name }}">
                <form action="{{ route('client.imgdestroy', $client->id) }}" method="post">

                    @csrf
                    @method('DELETE')
                    <input type="hidden" name="image" value="cover">

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteImage-thumbnail" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus thumbnail {{ $client->name }} ?</h5>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->thumb) }}" alt="{{ $client->name }}">
                <form action="{{ route('client.imgdestroy', $client->id) }}" method="post">

                    @csrf
                    @method('DELETE')
                    <input type="hidden" name="image" value="thumbnail">

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteImage-item" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus item {{ $client->name }} ?</h5>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->item) }}" alt="{{ $client->name }}">
                <form action="{{ route('client.imgdestroy', $client->id) }}" method="post">

                    @csrf
                    @method('DELETE')
                    <input type="hidden" name="image" value="item">

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/client-image.blade.php
<div class="modal fade" id="showImage-logo" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->logo) }}" alt="{{ $client->name }}">
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="showImage-background" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->background) }}" alt="{{ $client->name }}">
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="showImage-cover" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->cover) }}" alt="{{ $client->name }}">
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="showImage-thumb" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->thumb) }}" alt="{{ $client->name }}">
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="showImage-item" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <img class="img-thumbnail p-0 border-0 mx-auto d-block" src="{{ asset('storage/laraassets/images/brands/'. $client->item) }}" alt="{{ $client->name }}">
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/hire-create.blade.php
<div class="modal fade" id="create" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Open New Hire</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('hire.store') }}" method="post" autocomplete="off">
                    @csrf
                    <div class="form-group">
                        <label for="InputPosition">Position :</label>
                        <input type="text" name="position" class="form-control" id="InputPosition" placeholder="Nama Posisi">
                    </div>
                    <div class="form-group">
                        <label for="InputResponsibilities">Responsibilities :</label>
                        <div class="form-group">
                            <textarea class="tinyMCE" name="responsibilities"></textarea>
                        </div>
                        {{-- <textarea class="form-control resize-none" name="responsibilities" id="InputResponsibilities" cols="30" rows="10">{{ $job->responsibilities }}</textarea> --}}
                    </div>
                    <div class="form-group">
                        <label for="InputRequirement">Requirement :</label>
                        <div class="form-group">
                            <textarea class="tinyMCE" name="requirement"></textarea>
                        </div>
                        {{-- <textarea class="form-control resize-none" name="requirement" id="InputRequirement" cols="30" rows="10">{{ $job->requirement }}</textarea> --}}
                    </div>
                    <div class="text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/hire-delete.blade.php
<div class="modal fade" id="delete{{ $job->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus {{ $job->name }} ?</h5>
                <form action="{{ route('hire.destroy', $job->id) }}" method="post">

                    @csrf
                    @method('DELETE')

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/hire-edit.blade.php
<div class="modal fade" id="edit{{ $job->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Edit hire detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/admin/hire/{{ $job->id }}" method="post" autocomplete="off">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label for="inputStatus">Status :</label>
                        <select name="status" id="inputStatus" class="form-control w-25">
                            <option value="1" {!! $job->status == 1 ? 'selected' : '' !!}>Open</option>
                            <option value="0" {!! $job->status == 0 ? 'selected' : '' !!}>Closed</option>
                        </select>
                        {{-- <input type="checkbox" class="ozshowhide" name="flag" value="1" {!! $job->status == 1 ? 'checked' : '' !!} data-oz-switch data-off-color="default" data-on-color="success" data-token="{{ csrf_token() }}"> --}}
                    </div>
                    <div class="form-group">
                        <label for="InputPosition">Position :</label>
                        <input type="text" name="position" class="form-control" id="InputPosition" placeholder="Nama Posisi" value="{{ $job->position }}">
                    </div>
                    <div class="form-group">
                        <label for="InputResponsibilities">Responsibilities :</label>
                        <div class="form-group">
                            <textarea class="tinyMCE" name="responsibilities">{{ $job->responsibilities }}</textarea>
                        </div>
                        {{-- <textarea class="form-control resize-none" name="responsibilities" id="InputResponsibilities" cols="30" rows="10">{{ $job->responsibilities }}</textarea> --}}
                    </div>
                    <div class="form-group">
                        <label for="InputRequirement">Requirement :</label>
                        <div class="form-group">
                            <textarea class="tinyMCE" name="requirement">{{ $job->requirement }}</textarea>
                        </div>
                        {{-- <textarea class="form-control resize-none" name="requirement" id="InputRequirement" cols="30" rows="10">{{ $job->requirement }}</textarea> --}}
                    </div>
                    <div class="text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/section-create.blade.php
<div class="modal fade" id="newSection" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Create new section</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('section.store', ['slug' => 'client']) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('post')
                    <input type="hidden" name="id_brand" class="form-control" value="{{ $client->id }}">
                    <div class="form-group">
                        <label for="InputSectionName">Section Name</label>
                        <input type="text" name="section_name" class="form-control" id="InputSectionName" placeholder="Section Name">
                    </div>

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Back</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/section-delete.blade.php
<div class="modal fade" id="delete{{ $section->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus section {{ $section->section_name }} ?</h5>
                <form action="{{ route('section.destroy', ['slug' => 'client', 'section' => $section->id]) }}" method="post">

                    @csrf
                    @method('DELETE')

                    <button class="btn btn-sm btn-danger float-right">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/team-create.blade.php
<div class="modal fade" id="create" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('team.create') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('get')
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="InputNamaLengkap">Nama Lengkap</label>
                                <input type="text" name="fullName" class="form-control" id="InputNamaLengkap" placeholder="Nama Lengkap">
                            </div>
                            <div class="form-group">
                                <label for="InputNamaPanggilan">Nama Panggilan</label>
                                <input type="text" name="callName" class="form-control" id="InputNamaPanggilan" placeholder="Nama Panggilan">
                            </div>
                            <div class="form-group">
                                <label for="InputTitle">Title</label>
                                <input type="text" name="title" class="form-control" id="InputTitle" placeholder="Title">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img class="img-thumbnail p-0 border-0 mx-auto d-block mb-3" src="{{ asset('storage/laraassets/images/general/add-image.png') }}" alt="Upload Foto" width="200">
                            <div class="form-group mb-5">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="FotoDiri" name="newPhoto">
                                    <label class="custom-file-label" for="FotoDiri">Choice File</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/team-delete.blade.php
<div class="modal fade" id="delete{{ $user->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <h5>Ingin menghapus {{ $user->callName }} ?</h5>
                <form action="/admin/team/{{ $user->id }}" method="post">

                    @csrf
                    @method('DELETE')
                    <div class="text-right">
                        <button class="btn btn-sm btn-danger float-right">Hapus</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/team-edit.blade.php
<div class="modal fade" id="edit{{ $user->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="/admin/team/{{ $user->id }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="InputNamaLengkap">Nama Lengkap</label>
                                <input type="text" name="fullName" class="form-control" id="InputNamaLengkap" placeholder="Nama Lengkap" value="{{ $user->fullName }}">
                            </div>
                            <div class="form-group">
                                <label for="InputNamaPanggilan">Nama Panggilan</label>
                                <input type="text" name="callName" class="form-control" id="InputNamaPanggilan" placeholder="Nama Panggilan" value="{{ $user->callName }}">
                            </div>
                            <div class="form-group">
                                <label for="InputTitle">Title</label>
                                <input type="text" name="title" class="form-control" id="InputTitle" placeholder="Title" value="{{ $user->title }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img class="img-thumbnail p-0 border-0 mx-auto d-block mb-3" src="{{ asset('storage/laraassets/images/team/'. $user->photo) }}" alt="{{ $user->callName }}" width="200">
                            <input type="hidden" name="oldPhoto" value="{{ $user->photo }}">
                            <div class="form-group mb-5">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="FotoDiri" name="newPhoto">
                                    <label class="custom-file-label" for="FotoDiri">Choice File</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>